feed/urls.py
from django.urls import path
from .views import AddPostView, HomePageView, PostDetailView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),
    path('accounts/', include('allauth.urls')),
]

feed/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    
    def __str__(self):
        return self.text    

feed/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField(label="Description")

feed/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,DetailView,FormView
from django.contrib import messages
from feed.forms import PostForm

from feed.models import Post

# Create your views here.

class HomePageView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()
        return context
    
class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post


class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # Create a new Post
        new_object = Post.objects.create(
            text=form.cleaned_data['text']        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful')
        return super().form_valid(form)

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Default title {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">    
</head>
<body>
    {% load i18n %}
    <p class="p-2 bg-light"> <a href="/">{% trans 'Home' %}</a>
        {% if user.is_authenticated %}
            Hello, {{ user }} <a href="/accounts/logout">Logout</a>
        {% else %}
            <a href="/accounts/login">Login</a>
        {% endif %}
    </p>
    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{ message.tags }}{% else %}success{% endif %}  bg-gradient text-center text-white py-4">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="container">
    {% block content %}
    {% endblock content%}
    </div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ object.text }}{% endblock %}

{% block content %}
    <h3>POST Detail</h3>
    {{ object.text }}
{% endblock content%}

templates/home.html
{% extends "base.html" %}
{% block content %}
   <h3> POSTS</h3>
   <p><a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Create Post</a></p>
   <div class="row">
    {% for post in posts %}
        <div class="col-sm-6 col-md-3">
            <div class="card my-4">
                <div class="card-body">
                    <p class="card-text">{{ post.text }}</p>
                    <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Full Post</a>
                </div>
            </div>
        </div>
    {% empty %}
        <div class="col-sm-6 offset-3 text-center py-5 my-5">
            <h3>Welcome!</h3>
            <p>Add your first post?</p>
            <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Upload post</a>
        </div>
    {% endfor %}
</div>

{% endblock content%}

templates/new_post.html
{% extends "base.html" %}

{% block title %}Upload a new post{% endblock %}

{% block content %}
    <form method="POST" action="" enctype="multipart/form-data"
        <h2>Upload an post!</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button type="submit" class="btn btn-lg btn-success">Submit form</button>
        </div>
    </form>
{% endblock content%}